### ISSUE TITLE
Push and remove until

### ISSUE THREAD

**Issue by fernando-s97** [BilalShahid13/PersistentBottomNavBar#23]
My app has a necessity that is: there is a login screen. Once the user is logged in, he is taken to the main screen, which makes use of the persistent bottom bar. Once he access a tab, he cans exit his account, which will take him back to the login screen. How can I take the user back to the login screen and make it the only screen in the stack?

Currently I can take the user back to the login screen, but once he press the back button, he is taken back to the main screen

**Comment by BilalShahid13** [comment]
You need to pass the **context** of the login screen to the main screen. You can do that by passing the context as an argument. Then, when you want to logout, instead of **pushing** the login screen again, pop using the context of the login screen you just passed. This will take you back to the login screen and by pressing the back button, you wont go back to main screen.

It will be something like this `Navigator.pop(widget.loginScreenContext)` where *loginScreenContext* is the context of the previous screen.

But the recommended approach would be to you either `provider` or `bloc`. You will not need to pass the context over there because it will be a single screen which depending on state will decide whether to show the login screen or the home screen.

**Comment by fernando-s97** [comment]
Thank you!

**Comment by TharinduKetipe** [comment]
@BilalShahid13 
This solution is not working for me. I'm using following method to load the HomeScreen.
```
 Navigator.pushAndRemoveUntil(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      HomePage(title: 'Home', loginContext: context,)),
                              (Route<dynamic> route) => false,
                            );
```
I think your solution is working only for norma `push metho`d, isn't it?

**Comment by BilalShahid13** [comment]
@TharinduKetipe 

Try this 

```dart
 Navigator.of(context, rootNavigator: true).pushAndRemoveUntil(
                              MaterialPageRoute(
                                  builder: (context) =>
                                      HomePage(title: 'Home', loginContext: context,)),
                              (Route<dynamic> route) => false,
                            );
```
