### ISSUE TITLE
How to pushAndRemoveUntil screens after tapping some tab item?

### ISSUE THREAD

**Issue by d-apps** [BilalShahid13/PersistentBottomNavBar#4]
I have a List of Tabs and in the HomeScreen() I have other screens inside that I need to navigate to, for example, when I am at HomeScreen and navigate to the second screen, and later the third screen (screen after HomeScreen, HomeScreen1 - > Screen2 ->Screen3), if I tap the Home Icon from the BottomNavigationBar, I don't go back to HomeScreen.

Could you help me how can solve it?

**Comment by BilalShahid13** [comment]
The bottom tab items are **only** for navigating between tabs and not do something else. So tapping them will only change your current tab and not do something else.

I'm currently working on an update of the package which will allow people to attach their own custom widget with the nav bar. I think then you can modify your widget to do what you want even change the item tap behavior. Hopefully I will be able to release the update in a couple of days.

**Comment by BilalShahid13** [comment]
Check the latest version i.e. `1.3.0`. You can now customize what happens when you tap an item using your own custom style. If you want to use one of the package's style with this then head over the repository, copy that style's code and paste it in your project to use that as a `customWidget`.

I'm closing the issue now as it is now possible to achieve what you asked.

**Comment by SogoGolf** [comment]
Is it possible to "pushAndRemoveUntil" on the active tab only (whilst retaining the current state of the other tabs)? I tried this on 1.3 but it seemed to reset every (other) tab's navigation stack?
