### ISSUE TITLE
Animation open screen from bottom

### ISSUE THREAD

**Issue by felixferr** [BilalShahid13/PersistentBottomNavBar#57]
I, it is possible to open a screen view from bottom. It is the same animation than tik tok when add à vidéo Wiith middle button on nav bar.

**Comment by BilalShahid13** [comment]
Push your screen using the `pageTransitionAnimation` property in the navigator function.

```dart
pushNewScreen(
          context,
          screen: YourScreen(),
          pageTransitionAnimation: PageTransitionAnimation.slideUp,
);
```

**Comment by felixferr** [comment]
I spoken with a screen in the PersistentTabView

**Comment by BilalShahid13** [comment]
You mean you want slide up animation when opening a tab for the first time?

**Comment by felixferr** [comment]
Yes,

**Comment by BilalShahid13** [comment]
I just saw that TikTok animation. If you want to achieve the same effect then you will have to push your screen using the `PersistentBottomNavBarItem`'s **onPressed** property. It will be something like this:

```dart
List<PersistentBottomNavBarItem> _buildNavBarItems() {
    return [
       ....
      PersistentBottomNavBarItem(
        icon: Icon(),
        title: ("Your tab title"),
        onPressed: () => pushNewScreen(
          context,
          screen: YourScreen(),
          pageTransitionAnimation: PageTransitionAnimation.slideUp,
         );
      ),
      ......
   ];
}
```

Please note that you will have to pass a dummy screen in the screens array. Just pass a `Container()` instead of the screen.

**Comment by felixferr** [comment]
Thanks it's works !!
