### ISSUE TITLE
Issue with bottom tab withNavBar not working correctly 

### ISSUE THREAD

**Issue by mbrowerNDG** [BilalShahid13/PersistentBottomNavBar#69]
Using the example to illustrate the issue I am having 

on any tab, update 'navigate to second  screen '  button widget  with `withNavBar` set to **false**,
Second Screen correctly loads with no navbar
now update  'go to Third Screen'   button  widget with `withNavbar` set to **true**

expected behavior: 
Third screen loads with navbar,
actual behavior:
Third screen does not load with navbar

Is there any way to achieve this flow with this package?  Essentially I need to have a flow within in one of my tabs where subsequent navigation within this tab allows me to show navbar -> hide the navbar -> then show the navbar again?

**Comment by BilalShahid13** [comment]
Yes this the expected behaviour actually. Once you have chosen to push a screen without the navigation bar, you cannot make it appear back again as the navigator's root has changed.

But it can be achieved though by other means. You can either set the navigation bar's height to 0 when you push that second screen or set the property `hideNavigationBar` as *true*. Revert these to original values when you reach the third screen.

**Comment by abhijitrajmane** [comment]
How to achieve this ..please give me example

**Comment by BilalShahid13** [comment]
Sorry providing full example here is not the correct way as this has nothing to do with my package. But I will give you a hint that use [provider](https://pub.dev/packages/provider) to set the property `hideNavigationBar` of `PersistentTabView` depending on your needs.
