### ISSUE TITLE
incorrect layout on iPhone 11

### ISSUE THREAD

**Issue by SogoGolf** [BilalShahid13/PersistentBottomNavBar#8]
hi, i ran the example app on iPhone 11 and it was not rendering correctly for some reason. there's a large black space/area above the nav bar. Also, the nav bar is sitting too low.

XCode Version 11.4.1 (11E503a)
target: iOS 13.4

<img width="598" alt="2020-04-26_18-52-17" src="https://user-images.githubusercontent.com/19580787/80302736-3ab38b00-87ef-11ea-9222-45be8ed8d3dc.png">

**Comment by BilalShahid13** [comment]
I think you are probably running the sample project. That project is using the `customWidget` property with a custom widget. Your device is recognized as an iPhone with a notch (notched iPhones have more height to their bottom nav bar) so the default padding is being set as `90.0` as `navBarHeight` is left empty. But the height of that custom widget is `60.0`. That is why you are seeing that black bar. 

Set the `navBarHeight` as `60.0` and the black strip will disappear. Alternatively, you can set the height of the custom widget to `90.0`. That will also fix the issue with nav bar sitting too low :) 

This was just an explanation of what is happening. I would recommend using the styles that I have provided as you will not encounter this issue there because I'm handling the height and the padding for them. This is for developers who want to style their own navBar so I'm expecting them to handle this themselves.

I will fix the sample project and push an update soon. Thank you for letting me know!

**Comment by SogoGolf** [comment]
ahh lol yes your right! sorry about that. still good to know that the custom nav bar option is there etc. we may need it, shall see.

**Comment by BilalShahid13** [comment]
The sample project is updated. Also now you can provide a fixed height for all devices even in the custom widget scenario. It will handle it for notched devices.

Check the version `1.4.1` for this.
